// tt1 = [
//   ["CSE1","CS/AI2203(L) (E-LT4)","CS/AI2202(L) (E-LT4)","CS/AI2204(L) (E-LT4)","CS/AI2201(L) (E-LT4)","CS/AI2201(T) (E-LT4)","Lunch","MA2208(L) (E-LT4)","","MA2208(P) (CS LAB 1: FF)","MA2208(P) (CS LAB 1: FF)"],
//   ["CSE2","CS/AI2203(L) (E-LT4)","CS/AI2202(L) (E-LT4)","CS/AI2204(L) (E-LT4)","CS/AI2201(L) (E-LT4)","CS/AI2201(T) (E-LT4)","Lunch","MA2208(L) (E-LT4)","","MA2208(P) (CS LAB 2: FF)","MA2208(P) (CS LAB 2: FF)"],
//   ["CSE3","CS/AI2203(L) (E-LT4)","CS/AI2202(L) (E-LT4)","CS/AI2204(L) (E-LT4)","CS/AI2201(L) (E-LT4)","CS/AI2201(T) (E-LT4)","Lunch","MA2208(L) (E-LT4)","","",""],
//   ["CSE4","CS/AI2203(L) (E-LT4)","CS/AI2202(L) (E-LT4)","CS/AI2204(L) (E-LT4)","CS/AI2201(L) (E-LT4)","CS/AI2201(T) (E-LT4)","Lunch","MA2208(L) (E-LT4)","","",""],
//   ["CM","MA2209(L) (E-TR7)","CS/AI2202(L) (E-LT4)","CS/AI2204(L) (E-LT4)","MA2210(L) (E-TR7)","MA2211(L) (E-TR7)","Lunch","MA2208(L) (E-LT4)","MA2212(L) (E-TR7)","MA2213(L) (E-TR7)",""],
//   ["ECM1","","CS/AI2202(L) (E-LT4)","CS/AI2204(L) (E-LT4)","","EC 2205 (L) (E-CR5)","Lunch","MA2208(L) (E-LT4)","EC 2203 (L) (E-CR5)","EC 2203 (P)","EC 2203 (P)"],
//   ["ECM2","","CS/AI2204(L) (E-LT5)","MA2208(L) (E-LT5)","CS/AI2202(L) (E-LT5)","EC 2205 (L) (E-CR5)","Lunch","","EC 2203 (L) (E-CR5)","EC 2203 (P)","EC 2203 (P)"],
//   ["AI1","","CS/AI2204(L) (E-LT5)","MA2208(L) (E-LT5)","CS/AI2202(L) (E-LT5)","CS/AI2203(L) (E-LT5)","Lunch","CS/AI2201(L) (E-LT5)","CS/AI2201(T) (E-LT5)","CS/AI 2205 Programming workshop ","CS/AI 2205 Programming workshop "],
//   ["AI2","","CS/AI2204(L) (E-LT5)","MA2208(L) (E-LT5)","CS/AI2202(L) (E-LT5)","CS/AI2203(L) (E-LT5)","Lunch","CS/AI2201(L) (E-LT5)","CS/AI2201(T) (E-LT5)","CS/AI 2205 Programming workshop ","CS/AI 2205 Programming workshop "],
//   ["AI3","","CS/AI2204(L) (E-LT5)","MA2208(L) (E-LT5)","CS/AI2202(L) (E-LT5)","CS/AI2203(L) (E-LT5)","Lunch","CS/AI2201(L) (E-LT5)","CS/AI2201(T) (E-LT5)","CS/AI 2205 Programming workshop ","CS/AI 2205 Programming workshop "],
//   ["CE","CE 2206 (L) (E-TR8)","CE 2207 (L) (E-TR8)","MA2208(L) (E-LT5)","CE 2208 (L) (E-TR8)","CE 2209 (L) (E-TR8)","Lunch","CE 2206 (P)","CE 2206 (P)","CE 2207 (P)","CE 2207 (P)"],
//   ["ME","ME2201(L) (E-CR14)","ME2202(L) (E-CR14)","ME2206 (L) (E-CR14)","ME2208(L) (E-CR14)","ME2205 (L) (E-CR14)","Lunch","ME2208(P)","ME2208(P)","Digital Signal processing(8-15 wk, only MT) (E-CR14)",""],
//   ["MT","ME2201(L) (E-CR14)","ME2202(L) (E-CR14)","Digital Electronics(L) (E-CR16)","ME2208(L) (E-CR14)","Digital Electronics(T) (E-CR16)","Lunch","ME2208(P)","ME2208(P)","Digital Signal processing(8-15 wk, only MT) (E-CR14)",""],
//   ["NT","PH2203 (E-TR4)","PH2202 L (E-TR4)","MA2208(L) (E-LT5)","PH2201 (E-TR4)","CH2204 (E-TR4)","Lunch","PH2202 (Nano Tech) P","PH2202 (Nano Tech) P","PH2202 (Nano Tech) P","PH2202 (Nano Tech) P"],
//   ["CSE1","CS/AI2202(L) (E-LT4)","CS/AI2203(L) (E-LT4)","CS/AI2201(L) (E-LT4)","CS/AI2204(L) (E-LT4)","MA2208(L) (E-LT4)","Lunch","CS/AI 2205 Programming workshop ","CS/AI 2205 Programming workshop ","",""],
//   ["CSE2","CS/AI2202(L) (E-LT4)","CS/AI2203(L) (E-LT4)","CS/AI2201(L) (E-LT4)","CS/AI2204(L) (E-LT4)","MA2208(L) (E-LT4)","Lunch","CS/AI 2205 Programming workshop ","CS/AI 2205 Programming workshop ","",""],
//   ["CSE3","CS/AI2202(L) (E-LT4)","CS/AI2203(L) (E-LT4)","CS/AI2201(L) (E-LT4)","CS/AI2204(L) (E-LT4)","MA2208(L) (E-LT4)","Lunch","CS/AI 2205 Programming workshop ","CS/AI 2205 Programming workshop ","",""],
//   ["CSE4","CS/AI2202(L) (E-LT4)","CS/AI2203(L) (E-LT4)","CS/AI2201(L) (E-LT4)","CS/AI2204(L) (E-LT4)","MA2208(L) (E-LT4)","Lunch","CS/AI 2205 Programming workshop ","CS/AI 2205 Programming workshop ","",""],
//   ["CM","CS/AI2202(L) (E-LT4)","MA2208(P) (CS LAB 1: FF)","MA2208(P) (CS LAB 1: FF)","CS/AI2204(L) (E-LT4)","MA2208(L) (E-LT4)","Lunch","MA2209(L) (E-TR7)","MA2210(L) (E-TR7)","MA2212(L) (E-TR7)","MA2213(L) (E-TR7)"],
//   ["ECM1","CS/AI2202(L) (E-LT4)","MA2208(P) (CS LAB 1: FF)","MA2208(P) (CS LAB 1: FF)","CS/AI2204(L) (E-LT4)","MA2208(L) (E-LT4)","Lunch","EC 2203 (L) (E-CR5)","EC 2205 (P)","EC 2205 (P)",""],
//   ["ECM2","MA2208(L) (E-LT5)","CS/AI2204(L) (E-LT5)","CS/AI2202(L) (E-LT5)","","","Lunch","EC 2203 (L) (E-CR5)","EC 2205 (P)","EC 2205 (P)",""],
//   ["AI1","MA2208(L) (E-LT5)","CS/AI2204(L) (E-LT5)","CS/AI2202(L) (E-LT5)","","","Lunch","","","",""],
//   ["AI2","MA2208(L) (E-LT5)","CS/AI2204(L) (E-LT5)","CS/AI2202(L) (E-LT5)","CS/AI2203(L)  (E-LT5)","","Lunch","CS/AI2201(L) (E-LT5)","","",""],
//   ["AI3","MA2208(L) (E-LT5)","CS/AI2204(L) (E-LT5)","CS/AI2202(L) (E-LT5)","CS/AI2203(L)  (E-LT5)","","Lunch","CS/AI2201(L) (E-LT5)","","",""],
//   ["CE","MA2208(L) (E-LT5)","CE 2206 (L) (E-TR8)","","CS/AI2203(L)  (E-LT5)","CE 2208 (L) (E-TR8)","Lunch","CS/AI2201(L) (E-LT5)","CE 2209 (L) (E-TR8)","CE 2208 (P)","CE 2208 (P)"],
//   ["ME","ME2206 (L) (E-CR14)","ME2201(L) (E-CR14)","ME2202(L) (E-CR14)","ME2208(L) (E-CR14)","","Lunch","","Digital Signal processing(8-15 wk, only MT) (E-CR14)","ME2206 (L) (E-CR14)","ME2206 (L) (E-CR14)"],
//   ["MT","Digital Electronics(L) (E-CR16)","ME2201(L) (E-CR14)","ME2202(L) (E-CR14)","ME2208(L) (E-CR14)","","Lunch","","Digital Signal processing(8-15 wk, only MT) (E-CR14)","Digital Electronics (P)","Digital Electronics (P)"],
//   ["NT","MA2208(L) (E-LT5)","","PH2201 (E-TR4)","PH2203 (E-TR4)","CH2204 (E-TR4)","Lunch","CH2204 (P)","CH2204 (P)","",""],
//   ["CSE1","CS/AI2204(L) (E-LT4)","CS/AI2202(L) (E-LT4)","CS/AI2201(L) (E-LT4)","CS/AI2203(L) (E-LT4)","MA2208(L) (E-LT4)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["CSE2","CS/AI2204(L) (E-LT4)","CS/AI2202(L) (E-LT4)","CS/AI2201(L) (E-LT4)","CS/AI2203(L) (E-LT4)","MA2208(L) (E-LT4)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["CSE3","CS/AI2204(L) (E-LT4)","CS/AI2202(L) (E-LT4)","CS/AI2201(L) (E-LT4)","CS/AI2203(L) (E-LT4)","MA2208(L) (E-LT4)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["CSE4","CS/AI2204(L) (E-LT4)","CS/AI2202(L) (E-LT4)","CS/AI2201(L) (E-LT4)","CS/AI2203(L) (E-LT4)","MA2208(L) (E-LT4)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["CM","CS/AI2204(L) (E-LT4)","CS/AI2202(L) (E-LT4)","MA2214 (P)","MA2214 (P)","MA2208(L) (E-LT4)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["ECM1","CS/AI2204(L) (E-LT4)","CS/AI2202(L) (E-LT4)","","","MA2208(L) (E-LT4)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["ECM2","MA2208(L) (E-LT5)","","CS/AI2204(L) (E-LT5)","CS/AI2202(L) (E-LT5)","","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["AI1","MA2208(L) (E-LT5)","CS/AI2203(L) (E-LT5)","CS/AI2204(L) (E-LT5)","CS/AI2202(L) (E-LT5)","CS/AI2201(L) (E-LT5)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["AI2","MA2208(L) (E-LT5)","CS/AI2203(L) (E-LT5)","CS/AI2204(L) (E-LT5)","CS/AI2202(L) (E-LT5)","CS/AI2201(L) (E-LT5)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["AI3","MA2208(L) (E-LT5)","CS/AI2203(L) (E-LT5)","CS/AI2204(L) (E-LT5)","CS/AI2202(L) (E-LT5)","CS/AI2201(L) (E-LT5)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["CE","MA2208(L) (E-LT5)","CE 2206 (L) (E-TR8)","CE 2207 (L) (E-TR8)","CE 2209 (P)","CE 2209 (P)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["ME","ME2206 (L) (E-CR14)","ME2201(L) (E-CR14)","ME2202(T) (E-CR14)","ME2208(L) (E-CR14)","ME2201(T) (E-CR14)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["MT","","ME2201(L) (E-CR14)","ME2202(T) (E-CR14)","ME2208(L) (E-CR14)","ME2201(T) (E-CR14)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["NT","MA2208(L) (E-LT5)","","PH2201 (E-TR4)","PH2203 (E-TR4)","CH2204 (E-TR4)","Lunch","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc.","Seminars / Workshops etc."],
//   ["CSE1","CS/AI2202(L) (E-LT4)","","CS/AI2203(L) (E-LT4)","HS2203 (E-CR8)","","Lunch","","CS/AI2204(L) (E-LT4)","HS2202( fractal 1-7wk)",""],
//   ["CSE2","CS/AI2202(L) (E-LT4)","","CS/AI2203(L) (E-LT4)","HS2201 (E-CR10)","","Lunch","","CS/AI2204(L) (E-LT4)","HS2202( fractal 1-7wk)",""],
//   ["CSE3","CS/AI2202(L) (E-LT4)","","CS/AI2203(L) (E-LT4)","HS2203 (E-CR12)","","Lunch","","CS/AI2204(L) (E-LT4)","HS2202( fractal 1-7wk)",""],
//   ["CSE4","CS/AI2202(L) (E-LT4)","","CS/AI2203(L) (E-LT4)","HS2203 (E-CR16)","","Lunch","","CS/AI2204(L) (E-LT4)","HS2202( fractal 1-7wk)",""],
//   ["CM","CS/AI2202(L) (E-LT4)","MA2209(L) (E-TR7)","MA2210(L) (E-TR7)","MA2212(L) (E-TR7)","MA2213(L) (E-TR7)","Lunch","HS2203 (E-CR8)","CS/AI2204(L) (E-LT4)","HS2202( fractal 1-7wk)",""],
//   ["ECM1","CS/AI2202(L) (E-LT4)","EC 2203 (L) (E-CR5)","","EC 2205 (L) (E-CR5)","","Lunch","HS2203 (E-CR10)","CS/AI2204(L) (E-LT4)","",""],
//   ["ECM2","","EC 2203 (L) (E-CR5)","CS/AI2202(L) (E-LT5)","EC 2205 (L) (E-CR5)","CS/AI2202(L) (E-LT5)","Lunch","","","HS2203 (E-CR10)",""],
//   ["AI1","","HS2203 (E-CR8)","CS/AI2202(L) (E-LT5)","CS/AI2203(L) (E-LT5)","CS/AI2202(L) (E-LT5)","Lunch","","","MA2208(P) (CS LAB 1: FF) ","MA2208(P) (CS LAB 1: FF) "],
//   ["AI2","","HS2203 (E-CR10)","CS/AI2202(L) (E-LT5)","CS/AI2203(L) (E-LT5)","CS/AI2202(L) (E-LT5)","Lunch","","","MA2208(P) (CS LAB 2: FF) ","MA2208(P) (CS LAB 2: FF) "],
//   ["AI3","","HS2203 (E-CR12)","CS/AI2202(L) (E-LT5)","CS/AI2203(L) (E-LT5)","CS/AI2202(L) (E-LT5)","Lunch","MA2208(P) (CS LAB 2: FF) ","MA2208(P) (CS LAB 2: FF) ","",""],
//   ["CE","CE 2208 (L) (E-TR8)","","","","","Lunch","","","HS2203 (E-CR14)",""],
//   ["ME","","","Digital Signal processing(8-15 wk, only MT) (E-CR14)","ME2205 (L) (E-CR14)","","Lunch","","","HS2203 (E-CR14)",""],
//   ["MT","Digital Signal processing (T)(8-15 wk, only MT) (E-CR16)","","Digital Signal processing(8-15 wk, only MT) (E-CR14)","","","Lunch","MT 2204 (CAPSTON PROJECT) (Mechatronics Lab; SF)","MT 2204 (CAPSTON PROJECT) (Mechatronics Lab; SF)","HS2203 (E-CR14)",""],
//   ["NT","","","","","","Lunch","","","HS2203 (E-CR14)",""],
//   ["CSE1","","HS2203 (E-CR8)","","","","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["CSE2","","HS2203 (E-CR10)","","","","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["CSE3","","HS2203 (E-CR12)","","MA2208(P) (CS LAB 1: FF)","MA2208(P) (CS LAB 1: FF)","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["CSE4","","HS2201 (E-CR16)","","MA2208(P) (CS LAB 2: FF)","MA2208(P) (CS LAB 2: FF)","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["CM","","","HS2203 (E-TR7)","","","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["ECM1","","","HS2203 (E-CR10)","HS2202( fractal 1-7wk)","EC 2205 (L) (E-CR5)","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["ECM2","MA2208(P) (CS LAB 1: FF)","MA2208(P) (CS LAB 1: FF)","HS2203(E-CR12)","HS2202( fractal 1-7wk)","EC 2205 (L) (E-CR5)","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["AI1","","","HS2203 (E-CR16)","HS2202( fractal 1-7wk)","","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["AI2","","","HS2203(E-CR13)","HS2202( fractal 1-7wk)","","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["AI3","","","","HS2202( fractal 1-7wk)","HS2203 (E-CR16)","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["CE","MA2208(P) (CS LAB 1: FF)","MA2208(P) (CS LAB 1: FF)","CE 2207 (L) (E-TR8)","HS2202( fractal 1-7wk)","HS2203 (E-CR14)","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["ME","","","ME2205 (L) (E-CR14)","HS2202( fractal 1-7wk)","HS2203 (E-CR14)","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["MT","","","","HS2202( fractal 1-7wk)","HS2203 (E-CR14)","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["NT","MA2208(P) (CS LAB 1: FF)","MA2208(P) (CS LAB 1: FF)","","HS2202( fractal 1-7wk)","HS2203 (E-CR14)","Lunch","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)","HS 2201 (Design thinking) (E-LT3 & E-LT4)"],
//   ["CSE1","","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","","","Lunch","","","",""],
//   ["CSE2","","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","","","Lunch","","","",""],
//   ["CSE3","","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","","","Lunch","","","",""],
//   ["CSE4","","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","","","Lunch","","","",""],
//   ["CM","","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","","","Lunch","","","",""],
//   ["ECM1","","","","","","Lunch","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","",""],
//   ["ECM2","","","","","","Lunch","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","",""],
//   ["AI1","","","","","","Lunch","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","",""],
//   ["AI2","","","","","","Lunch","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","",""],
//   ["AI3","","","","","","Lunch","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","",""],
//   ["CE","","","","","","Lunch","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","",""],
//   ["ME","","","","","","Lunch","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","",""],
//   ["MT","","","","","","Lunch","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","",""],
//   ["NT","","","","","","Lunch","HS2202( fractal 1-7wk)","HS2202( fractal 1-7wk)","",""]
// ];

tt1 = [
  ["CSE1 (62)","CS/AI 3102(Operating sytsem) Dr. Yayati (ELT 4)","CS 3105 (Object oriented programming) Dr. Veeraiah (EL -4)","CS/AI 3102 (P) (Operating system) (IT2 block) ","CS/AI 3102 (P) (Operating system) (IT2 block) ","Lunch","","","CS/AI3103 (Data base management system) Dr.  Prafulla (Auditorium)","CS 3106 (Microprocessors and Interfacing) Dr. Praveen (ELT 4)",""],
  ["CSE2 (62)","CS/AI 3102(Operating sytsem) Dr. Yayati (ELT 4)","CS 3105 (Object oriented programming) Dr. Veeraiah (EL -4)","CS/AI 3102 (P) (Operating system) (IT2 block) ","CS/AI 3102 (P) (Operating system) (IT2 block) ","Lunch","","","CS/AI3103 (Data base management system) Dr.  Prafulla (Auditorium)","CS 3106 (Microprocessors and Interfacing) Dr. Praveen (ELT 4)",""],
  ["CSE3 (62)","CS/AI 3102(Operating sytsem) Dr. Yayati (ELT 4)","CS 3105 (Object oriented programming) Dr. Veeraiah (EL -4)","","","Lunch","CS/AI 3102 (P) (Operating system)  (IT2 block) ","CS/AI 3102 (P) (Operating system)  (IT2 block) ","CS/AI3103 (Data base management system) Dr.  Prafulla (Auditorium)","CS 3106 (Microprocessors and Interfacing) Dr. Praveen (ELT 4)",""],
  ["CSE4 (60)","CS/AI 3102(Operating sytsem) Dr. Yayati (ELT 4)","CS 3105 (Object oriented programming) Dr. Veeraiah (EL -4)","","","Lunch","CS/AI 3102 (P) (Operating system)  (IT2 block) ","CS/AI 3102 (P) (Operating system)  (IT2 block) ","CS/AI3103 (Data base management system) Dr.  Prafulla (Auditorium)","CS 3106 (Microprocessors and Interfacing) Dr. Praveen (ELT 4)",""],
  ["CM (19)","CS/AI 3102(Operating sytsem) Dr. Yayati (ELT 4)","MA3115 (Computational Methods for PDE) Dr. Satyanarayan (ECR 11)","MA3116 (Financial Maths) Dr. Manoj (ECR 15)","MA3117 (Advanced Linear Algebra ) Dr. Ravi Babu (ECR 15)","Lunch","CS/AI 3102 (P) (Operating system)  (IT2 block) ","CS/AI 3102 (P) (Operating system)  (IT2 block) ","CS/AI3103 (Data base management system) Dr.  Prafulla (Auditorium)","",""],
  ["ECM (79)","EC 3109 (P)(Digital Signal Processing)  ","EC 3109 (P)(Digital Signal Processing)  ","EC 3107 (Web Technologies)  Dr. Yashwanth (ECR 5)","EC3101 (Optimization Techniques for AI) Dr. Bhanu Kiran ( ECR 5)","Lunch","EC 3103 (Programmable devices) Dr. Bharghava (ECR 5)","EC 3109 (Digital Signal Processing) Dr. Subbarao (ECR 5)","CS/AI3103 (Data base management system) Dr.  Prafulla (Auditorium)","EC 3103 (P) (Programmable devices)","EC 3103 (P) (Programmable devices)"],
  ["ECM (79)","EC 3103 (P) (Programmable devices)","EC 3103 (P) (Programmable devices)","EC 3107 (Web Technologies)  Dr. Yashwanth (ECR 5)","EC3101 (Optimization Techniques for AI) Dr. Bhanu Kiran ( ECR 5)","Lunch","EC 3103 (Programmable devices) Dr. Bharghava (ECR 5)","EC 3109 (Digital Signal Processing) Dr. Subbarao (ECR 5)","CS/AI3103 (Data base management system) Dr.  Prafulla (Auditorium)","EC 3109 (P)(Digital Signal Processing)  ","EC 3109 (P)(Digital Signal Processing)  "],
  ["AI1 (65)","AI 3105 (P) (Computer Network-Lite) (IT2 block)","AI 3105 (P) (Computer Network-Lite) (IT2 block)","","AI 3105 (Computer Network-Lite) Dr. Mahesh (ELT 1)\n","Lunch","CS/AI 3102(Operating system) Dr. Neeraj (ELT 2)","AI 3106 (T1 Foundation of NLP) Dr. Avinash (ELT 2)","CS/AI3103 (Data base management system) Dr.  Prafulla (Auditorium)","CS/AI 3102 (P) (Operating system) (IT2 block)","CS/AI 3102 (P) (Operating system) (IT2 block)"],
  ["AI2 (65)","AI 3105 (P) (Computer Network-Lite) (IT2 block)","AI 3105 (P) (Computer Network-Lite) (IT2 block)","","AI 3105 (Computer Network-Lite) Dr. Mahesh (ELT 1)\n","Lunch","CS/AI 3102(Operating system) Dr. Neeraj (ELT 2)","AI 3106 (T1 Foundation of NLP) Dr. Avinash (ELT 2)","CS/AI3103 (Data base management system) Dr.  Prafulla (Auditorium)","CS/AI 3102 (P) (Operating system) (IT2 block)","CS/AI 3102 (P) (Operating system) (IT2 block)"],
  ["AI3 (64)","AI 3105 (P) (Computer Network-Lite) (IT2 block)","AI 3105 (P) (Computer Network-Lite) (IT2 block)","","AI 3105 (Computer Network-Lite) Dr. Mahesh (ELT 1)\n","Lunch","CS/AI 3102(Operating system) Dr. Neeraj (ELT 2)","AI 3106 (T1 Foundation of NLP) Dr. Avinash (ELT 2)","CS/AI3103 (Data base management system) Dr.  Prafulla (Auditorium)","CS/AI 3102 (P) (Operating system) (IT2 block)","CS/AI 3102 (P) (Operating system) (IT2 block)"],
  ["CE (17)","","CE3113 (Reinforced Concrete Design) Dr. JayaPrakash (ECR 10)","CE3115 (Water Resources Engineering) Dr. Prabhakar (ECR 10)","CE3111 (Construction Technology) Dr. Deepti (ECR-10)","Lunch","CE3110 (Transportation Engineering) Dr. Jahnabi (ECR 10)","","","",""],
  ["ME (13)","ME3113 (Design of Machine Elements) Dr. Kondaiah (ECR 12)","ME3103 (Introduction to Robotics) /MT3102 (Robotics 1) Dr. Deep (ECR 12)","ME3102 (Measurement and Instrumentation)  Dr. Ravi (ECR 12)","ME3104 (Heat and Mass Transfer) Dr. Sebastian (ECR 12)","Lunch","","","","",""],
  ["MT (20)","ME3113 (Design of Machine Elements) Dr. Kondaiah (ECR 12)","ME3103 (Introduction to Robotics) /MT3102 (Robotics 1) Dr. Deep (ECR 12)","ME3102 (Measurement and Instrumentation)  Dr. Ravi (ECR 12)","ME3101 (Manufacturing and Automated Processes) Dr. Abhijit (ECR 14)","Lunch","MT3105 (Power Electronics and Control System)Dr. Pavani (ECR 12)","","","",""],
  ["NT (6)","PH 3101 (Advanced Nanomaterials and Devices) Dr. Dibkar RC (ECR 16)","MA3115 (Computational Methods for PDE) Dr. Satyanarayan (ECR 11)","CH3105 (Nanostructure Characterization Dr. Gomathi (ECR 16)","","Lunch","","","","PH3101 (P) (Advanced Nanomaterials and Devices) Dr. Anil","PH3101 (P) (Advanced Nanomaterials and Devices) Dr. Anil"],
  ["CSE1 (62)","CS/AI 3102(Operating sytsem) Dr. Shabnam (ELT 4)","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (Auditorium)","","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT 4)","Lunch","CS 3106 (P) (Microprocessors and Interfacing) (IT2 block)","CS 3106 (P) (Microprocessors and Interfacing) (IT2 block)","","CS 3106 (Microprocessors and Interfacing) Dr. Praveen (ELT 6)","CS 3105 (Object oriented programming) Dr. Veeraiah (ELT 4)"],
  ["CSE2 (62)","CS/AI 3102(Operating sytsem) Dr. Shabnam (ELT 4)","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (Auditorium)","","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT 4)","Lunch","CS 3106 (P) (Microprocessors and Interfacing) (IT2 block)","CS 3106 (P) (Microprocessors and Interfacing) (IT2 block)","","CS 3106 (Microprocessors and Interfacing) Dr. Praveen (ELT 6)","CS 3105 (Object oriented programming) Dr. Veeraiah (ELT 4)"],
  ["CSE3 (62)","CS/AI 3102(Operating sytsem) Dr. Shabnam (ELT 4)","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (Auditorium)","","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT 4)","Lunch","","","","CS 3106 (Microprocessors and Interfacing) Dr. Praveen (ELT 6)","CS 3105 (Object oriented programming) Dr. Veeraiah (ELT 4)"],
  ["CSE4 (60)","CS/AI 3102(Operating sytsem) Dr. Shabnam (ELT 4)","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (Auditorium)","","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT 4)","Lunch","","","","CS 3106 (Microprocessors and Interfacing) Dr. Praveen (ELT 6)","CS 3105 (Object oriented programming) Dr. Veeraiah (ELT 4)"],
  ["CM (19)","CS/AI 3102(Operating sytsem) Dr. Shabnam (ELT 4)","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (Auditorium)","MA3115 (Computational Methods for PDE) Dr. Satyanarayan (ECR 2)","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT 4)","Lunch","MA3116 (Financial Maths) Dr. Manoj (ECR 2)","MA3117 (Advanced Linear Algebra ) Dr. Ravi Babu (ECR 2)","","",""],
  ["ECM (79)","EC 3109 (Digital Signal Processing) Dr. Subbarao (ECR 5)","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (Auditorium)","","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT 4)","Lunch","EC 3103 (Programmable devices) Dr. Bharghava (ECR 5)","EC 3107 (Web Technologies) Dr. Yashwanth (ECR 5)","","EC 3107 (P) (Web Technologies) ","EC 3107 (P) (Web Technologies) "],
  ["ECM (79)","EC 3109 (Digital Signal Processing) Dr. Subbarao (ECR 5)","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (Auditorium)","","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT 4)","Lunch","EC 3103 (Programmable devices) Dr. Bharghava (ECR 5)","EC 3107 (Web Technologies) Dr. Yashwanth (ECR 5)","","EC 3107 (P) (Web Technologies) ","EC 3107 (P) (Web Technologies) "],
  ["AI1 (65)","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (Auditorium)","CS/AI 3102(Operating system) Dr. Neeraj (ELT 4)","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT 4)","Lunch","","","AI 3106 (T1 Foundation of NLP) Dr. Avinash Chauhan (ELT 4)","AI 3107  (T2 Digital Image processing) Dr. Deepti Mishra (ELT 4)",""],
  ["AI2 (65)","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (Auditorium)","CS/AI 3102(Operating system) Dr. Neeraj (ELT 4)","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT 4)","Lunch","","","AI 3106 (T1 Foundation of NLP) Dr. Avinash Chauhan (ELT 4)","AI 3107  (T2 Digital Image processing) Dr. Deepti Mishra (ELT 4)",""],
  ["AI3 (64)","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (Auditorium)","CS/AI 3102(Operating system) Dr. Neeraj (ELT 4)","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT 4)","Lunch","","","AI 3106 (T1 Foundation of NLP) Dr. Avinash Chauhan (ELT 4)","AI 3107  (T2 Digital Image processing) Dr. Deepti Mishra (ELT 4)",""],
  ["CE (17)","","CE3115 (Water Resources Engineering) Dr. Prabhakar (ECR 3)","CE3114 (Soil Mechanics) Dr. HariPrasad (ECR 3)","CE3113 (Reinforced Concrete Design) Dr. JayaPrakash (ECR 2)","Lunch","CE3110 (Transportation Engineering) Dr. Jahnabi (ECR 3)","CE3112 (P) (Computing Lab) Dr. HariPrasad/Dr. Dilip","CE3112 (P) (Computing Lab) Dr. HariPrasad/Dr. Dilip","CE3112 (P) (Computing Lab) Dr. HariPrasad/Dr. Dilip","CE3112 (P) (Computing Lab) Dr. HariPrasad/Dr. Dilip"],
  ["ME (13)","ME4069 (Stream course I: FEM+CFD combined fractal)  Dr. Gouripriya (ECR 2)","ME3113 (Design of Machine Elements) Dr. Kondaiah (ECR 2)","ME3103 (Introduction to Robotics)/MT3102 (Robotics 1) Dr. Deep (ECR 12)","ME3104 (Heat and Mass Transfer) Dr. Sebastian (ECR 12)","Lunch","","","ME3108 (Metrology and CAM) Dr. Praveen Konka (ECR 3)","",""],
  ["MT (20)","ME3101 (Manufacturing and Automated Processes) Dr. Abhijit (ECR 14)","ME3113 (Design of Machine Elements) Dr. Kondaiah (ECR 2)","ME3103 (Introduction to Robotics)/MT3102 (Robotics 1) Dr. Deep (ECR 12)","MT3105 (Power Electronics and Control System) Dr. Pavani (ECR 8)\n","Lunch","MT3107 (BioMedical Instrumentation) Dr. Ashish Kumar Sahu (ECR 10)","MT3104 (Capston Project) Dr. Sebasteian (ECR 10)","MT3104 (Capston Project) Dr. Sebasteian (ECR 10)","",""],
  ["NT (6)","PH 3101 (Advanced Nanomaterials and Devices)  Anil Annandi (ECR 16)","PH3102 (Nano  Photonics)  Jayasri Dontabhaktuni (ECR 16)","MA3115 (Computational Methods for PDE) Dr. Satyanarayan (ECR 16)","CH3105 (Nanostructure Characterization Dr. Gomathi (ECR 16)","Lunch","PH3102 (P) (Nano Photonics) Dr. Jayasri","PH3102 (P) (Nano Photonics) Dr. Jayasri","CH3105 (P) (Nanostructure Characterization) Dr. Gomathi (ECR 2)","CH3105 (P) (Nanostructure Characterization) Dr. Gomathi (ECR 2)","PH3101 (Advanced Nanomaterials and Devices) Dr. Anil Annandi (ECR 8 )"],
  ["CSE1 (62)","CS/AI 3102(Operating system) Dr. Yayati (ELT 4)","","CS/AI3103 (P)(Data base management system) (COMP LAB 1)","CS/AI3103 (P)(Data base management system) (COMP LAB 1)","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT-4)"],
  ["CSE2 (62)","CS/AI 3102(Operating system) Dr. Yayati (ELT 4)","","CS/AI3103 (P)(Data base management system) (COMP LAB 1)","CS/AI3103 (P)(Data base management system) (COMP LAB 1)","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT-4)"],
  ["CSE3 (62)","CS/AI 3102(Operating system) Dr. Yayati (ELT 4)","","CS/AI3103 (P)(Data base management system) (COMP LAB 1)","CS/AI3103 (P)(Data base management system) (COMP LAB 1)","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT-4)"],
  ["CSE4 (60)","CS/AI 3102(Operating system) Dr. Yayati (ELT 4)","","","","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT-4)"],
  ["CM (19)","CS/AI 3102(Operating system) Dr. Yayati (ELT 4)","","MA3116 (Financial Maths) Dr. Manoj (ECR 14)","MA3117 (Advanced Linear Algebra ) Dr. Ravi Babu (ECR 14)","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT-4)"],
  ["ECM (79)","","EC3101 (Optimization Techniques for AI) Dr. Bhanu Kiran (ECR 4)","","","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT-4)"],
  ["ECM (79)","","EC3101 (Optimization Techniques for AI) Dr. Bhanu Kiran (ECR 4)","","","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT-4)"],
  ["AI1 (65)","CS/AI3103 (P)(Data base management system) (COMP LAB 1)","CS/AI3103 (P)(Data base management system) (COMP LAB 1)","CS/AI 3102(Operating sytsem)Dr. shabnam (ELT 2)","","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT-4)"],
  ["AI2 (65)","CS/AI3103 (P)(Data base management system) (COMP LAB 1)","CS/AI3103 (P)(Data base management system) (COMP LAB 1)","","","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT-4)"],
  ["AI3 (64)","CS/AI3103 (P)(Data base management system) (COMP LAB 1)","CS/AI3103 (P)(Data base management system) (COMP LAB 1)","","","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop","CS/AI3103 (Data base management system) Dr.  Prafulla (ELT-4)"],
  ["CE (17)","","CE3115 (Water Resources Engineering) Dr. Prabhakar (ECR 2)","CE3114 (Soil Mechanics) Dr. HariPrasad (ECR 2)","CE3113 (Reinforced Concrete Design) Dr. JayaPrakash (ECR 2)","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop",""],
  ["ME (13)","ME3108 (Metrology and CAM) Dr. Praveen Konka (ECR 2)","ME3103 (Introduction to Robotics)/MT3102 (Robotics 1) Dr. Deep (ECR 3)","ME3102 (Measurement and Instrumentation)  Dr. Ravi (ECR 12)","ME3104 (Heat and Mass Transfer) Dr. Sebastian (ECR 3)","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop",""],
  ["MT (20)","","ME3103 (Introduction to Robotics)/MT3102 (Robotics 1) Dr. Deep (ECR 3)","","MT3105 (Power Electronics and Control System) Dr. Pavani (ECR 12)","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop",""],
  ["NT (6)","PH 3101 (P) Advanced Nanomaterials and Devices) Dr. Anil (ECR 14) ","PH 3101 (P) Advanced Nanomaterials and Devices) Dr. Anil (ECR 14) ","CH3106 (Molecular Spectroscopy) Dr. Venkataraman (ETR )","PH 3101 (Advanced Nanomaterials and Devices)  Dr. Dibkar RC (ECR 10)","Lunch","Seminar/workshop","Seminar/workshop","Seminar/workshop","Seminar/workshop",""],
  ["CSE1 (62)","","","CS 3105 (P) (Object oriented programming)(IT2 Block)","CS 3105 (P) (Object oriented programming)(IT2 Block)","Lunch","CS 3106 (P) (Microprocessors and Interfacing) (IT2 block)","CS 3106 (P) (Microprocessors and Interfacing) (IT2 block)","Elective","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 1 and LAB 2)","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 1 and LAB 2)"],
  ["CSE2 (62)","","","CS 3105 (P) (Object oriented programming)(IT2 Block)","CS 3105 (P) (Object oriented programming)(IT2 Block)","Lunch","CS 3106 (P) (Microprocessors and Interfacing) (IT2 block)","CS 3106 (P) (Microprocessors and Interfacing) (IT2 block)","Elective","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 1 and LAB 2)","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 1 and LAB 2)"],
  ["CSE3 (62)","","","","","Lunch","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 1 and LAB 2)","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 1 and LAB 2)","Elective","CS 3105 (P) (Object oriented programming) (IT2 Block)","CS 3105 (P) (Object oriented programming) (IT2 Block)"],
  ["CSE4 (60)","CS/AI3103 (P)(Data base management system) (comp lab 1 FF)","CS/AI3103 (P)(Data base management system) (comp lab 1 FF)","","","Lunch","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 1 and LAB 2)","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 1 and LAB 2)","Elective","CS 3105 (P) (Object oriented programming) (IT2 Block)","CS 3105 (P) (Object oriented programming) (IT2 Block)"],
  ["CM (19)","CS/AI3103 (P)(Data base management system) (comp lab 1 FF)","CS/AI3103 (P)(Data base management system) (comp lab 1 FF)","MA3115 (Computational Methods for PDE) Dr. Satyanarayan (ECR-3)","","Lunch","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 1 and LAB 2)","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 1 and LAB 2)","Elective","",""],
  ["ECM (79)","CS/AI3103 (P)(Data base management system) (comp lab 1 FF)","CS/AI3103 (P)(Data base management system) (comp lab 1 FF)","EC 3107 (P) (Web Technologies) ","EC 3107 (P) (Web Technologies) ","Lunch","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 3)","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 3)","Elective","",""],
  ["ECM (79)","CS/AI3103 (P)(Data base management system) (comp lab 1 FF)","CS/AI3103 (P)(Data base management system) (comp lab 1 FF)","EC 3107 (P) (Web Technologies) ","EC 3107 (P) (Web Technologies) ","Lunch","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 3)","CS/AI 3101 (P)(Design and Analysis of Algorithms) (COMP LAB 3)","Elective","",""],
  ["AI1 (65)","","AI 3107  (T2 Digital Image processing) Dr. Deepti Mishra (ELT 6)","CS/AI 3101 (P)(Design and Analysis of Algorithms)(IT 2 block)","CS/AI 3101 (P)(Design and Analysis of Algorithms)(IT 2 block)","Lunch","AI 3106 (T1 Foundation of NLP) Dr. Avinash Chauhan (ELT 4)","","Elective","",""],
  ["AI2 (65)","","AI 3107  (T2 Digital Image processing) Dr. Deepti Mishra (ELT 6)","CS/AI 3101 (P)(Design and Analysis of Algorithms)(IT 2 block)","CS/AI 3101 (P)(Design and Analysis of Algorithms)(IT 2 block)","Lunch","AI 3106 (T1 Foundation of NLP) Dr. Avinash Chauhan (ELT 4)","","Elective","",""],
  ["AI3 (64)","","AI 3107  (T2 Digital Image processing) Dr. Deepti Mishra (ELT 6)","CS/AI 3101 (P)(Design and Analysis of Algorithms)(IT 2 block)","CS/AI 3101 (P)(Design and Analysis of Algorithms)(IT 2 block)","Lunch","AI 3106 (T1 Foundation of NLP) Dr. Avinash Chauhan (ELT 4)","","Elective","",""],
  ["CE (17)","","","CE3114 (Soil Mechanics) Dr. HariPrasad (ECR 2)","CE3111 (Construction Technology) Dr. Deepti (ECR 2)","Lunch","CE3114 (P) (Soil Mechanics Lab) Dr. HariPrasad","CE3114 (P) (Soil Mechanics Lab) Dr. HariPrasad","Elective","",""],
  ["ME (13)","ME4069 (Stream course I: FEM+CFD combined fractal) (P)","ME4069 (Stream course I: FEM+CFD combined fractal) (P)","ME3102 (P) (Measurement and Instrumentation) Dr. Ravi (Measurement and instrumentation lab)","ME3102 (P) (Measurement and Instrumentation) Dr. Ravi (Measurement and instrumentation lab)","Lunch","ME3101 (P) (Fluid and Solid Mechanics lab) Fluid Mechanics lab (near workshop) ","ME3101 (P) (Fluid and Solid Mechanics lab) Fluid Mechanics lab (near workshop) ","Elective","ME3113 (Design of Machine Elements) Dr. Kondaiah (ECR 2)",""],
  ["MT (20)","MT3107 (BioMedical Instrumentation) Dr. Ashish Kumar (ECR 2)","","ME3101 (P) (Manufacturing and Automated Processes) Dr. Abhijit \t\n(Mechanical workshop)","ME3101 (P) (Manufacturing and Automated Processes) Dr. Abhijit \t\n(Mechanical workshop)","Lunch","ME3102 (P) (Measurement and Instrumentation)(Measurement and instrumentation lab)","ME3102 (P) (Measurement and Instrumentation)(Measurement and instrumentation lab)","Elective","ME3113 (Design of Machine Elements) Dr. Kondaiah (ECR 2)",""],
  ["NT (6)","CH3106 (Molecular Spectroscopy) Dr. Venkataraman (ECR 3)","PH3102 (Nano  Photonics) Jayasri Dontabhaktuni (ECR 3)","MA3115 (Computational Methods for PDE) Dr. Satyanarayan (ECR-3)","CH3105 (Nanostructure Characterization Dr. Gomathi (ECR 3)","Lunch","","","Elective","","PH3101 (Advanced Nanomaterials and Devices) Dr. Dibkar RC (ECR 8)"],
  ["CSE1 (62)","CS3104 (Programming Workshop) Dr. Sukhija (IT2 block)","CS3104 (Programming Workshop) Dr. Sukhija (IT2 block)","","Elective","Lunch","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (AUDITORIUM) ","","","",""],
  ["CSE2 (62)","CS3104 (Programming Workshop) Dr. Sukhija (IT2 block)","CS3104 (Programming Workshop) Dr. Sukhija (IT2 block)","","Elective","Lunch","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (AUDITORIUM) ","","","",""],
  ["CSE3 (62)","CS3104 (Programming Workshop) Dr. Sukhija (IT2 block)","CS3104 (Programming Workshop) Dr. Sukhija (IT2 block)","","Elective","Lunch","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (AUDITORIUM) ","","","CS 3106 (P) (Microprocessors and Interfacing)  (IT2 block)","CS 3106 (P) (Microprocessors and Interfacing)  (IT2 block)"],
  ["CSE4 (60)","CS3104 (Programming Workshop) Dr. Sukhija (IT2 block)","CS3104 (Programming Workshop) Dr. Sukhija (IT2 block)","","Elective","Lunch","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (AUDITORIUM) ","","","CS 3106 (P) (Microprocessors and Interfacing)  (IT2 block)","CS 3106 (P) (Microprocessors and Interfacing)  (IT2 block)"],
  ["CM (19)","MA 3118 (Programming Workshop)  Manoj Kumar Yadav (comp Lab 2)\n","MA 3118 (Programming Workshop)  Manoj Kumar Yadav (comp Lab 2)\n","MA3115 (T) (Computational Methods for PDE) Dr. Satyanarayan (ECR 10)","Elective","Lunch","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (AUDITORIUM) ","","","",""],
  ["ECM1 (79)","","EC3101 (T) (Optimization Techniques for AI) Dr. Bhanu Kiran (ECR 13)","","Elective","Lunch","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (AUDITORIUM) ","","","EC3101 (Optimization Techniques for AI) Dr. Bhanu Kiran (ECR 13)",""],
  ["ECM1 (79)","","EC3101 (T) (Optimization Techniques for AI) Dr. Bhanu Kiran (ECR 13)","","Elective","Lunch","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (AUDITORIUM) ","","","EC3101 (Optimization Techniques for AI) Dr. Bhanu Kiran (ECR 13)",""],
  ["AI1 (65)","","","","Elective","Lunch","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (AUDITORIUM) ","AI3104 (Programming Workshop) Dr. Nidhi (IT2 block)","AI3104 (Programming Workshop) Dr. Nidhi (IT2 block)","",""],
  ["AI2 (65)","","","","Elective","Lunch","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (AUDITORIUM) ","AI3104 (Programming Workshop) Dr. Nidhi (IT2 block)","AI3104 (Programming Workshop) Dr. Nidhi (IT2 block)","",""],
  ["AI3 (64)","","","","Elective","Lunch","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed  (AUDITORIUM) ","AI3104 (Programming Workshop) Dr. Nidhi (IT2 block)","AI3104 (Programming Workshop) Dr. Nidhi (IT2 block)","",""],
  ["CE (17)","","CE3113 (T) (Reinforced Concrete Design) Dr. JayaPrakash (ECR 3)","CE3110 (Transportation Engineering) Dr. Jahnabi (ECR 3)","Elective","Lunch","CE3110 (P) (Transportation Engineering Lab) Dr. Jahnabi","CE3110 (P) (Transportation Engineering Lab) Dr. Jahnabi","","",""],
  ["ME (13)","ME4069 (Stream course I: FEM+CFD combined fractal) Dr. Prasad (ECR 3)","ME3104 (T) (Heat and Mass Transfer) Dr. Sebastian (ECR 14)","ME3113 (T) (Design of Machine Elements) Dr. Kondaiah (ECR 14)","Elective","Lunch","ME3108 (P) (Metrology and CAM)","ME3108 (P) (Metrology and CAM)","","",""],
  ["MT (20)","","MT3105 (T) (Power Electronics and Control System) Dr. Pavani (ECR 12)","ME3113 (T) (Design of Machine Elements) Dr. Kondaiah (ECR 14)","Elective","Lunch","MT3107 (BioMedical Instrumentation) Dr. Ashish Kumar Sahu (ECR 8)","","","",""],
  ["NT (6)","CH3106 (Molecular Spectroscopy) Dr. Venkataraman (ECR 12)","PH3102 (Nano  Photonics)  Dr. Jayasri Dontabhaktuni (ECR 10)","MA3115 (T) (Computational Methods for PDE) Dr. Satyanarayan (ECR-10)","Elective","Lunch","","","","","PH3101 (Advanced Nanomaterials and Devices)  Dr. Anil Annandi (ECR 8)"],
  ["CSE1 (62)","","","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed (AUDITORIUM)","Lunch","","","","",""],
  ["CSE2 (62)","","","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed (AUDITORIUM)","Lunch","","","","",""],
  ["CSE3 (62)","","","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed (AUDITORIUM)","Lunch","","","","",""],
  ["CSE4 (60)","","","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed (AUDITORIUM)","Lunch","","","","",""],
  ["CM (19)","","","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed (AUDITORIUM)","Lunch","","","","",""],
  ["ECM1 (79)","","","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed (AUDITORIUM)","Lunch","","","","",""],
  ["ECM1 (79)","","","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed (AUDITORIUM)","Lunch","","","","",""],
  ["AI1 (65)","","","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed (AUDITORIUM)","Lunch","AI 3107 (P) (T2 Digital Image processing) (IT2 block)","AI 3107 (P) (T2 Digital Image processing) (IT2 block)","","",""],
  ["AI2 (65)","","","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed (AUDITORIUM)","Lunch","AI 3107 (P) (T2 Digital Image processing) (IT2 block)","AI 3107 (P) (T2 Digital Image processing) (IT2 block)","","",""],
  ["AI3 (64)","","","","CS/AI 3101(Design and Analysis of Algorithms) Dr. Tauheed (AUDITORIUM)","Lunch","AI 3107 (P) (T2 Digital Image processing) (IT2 block)","AI 3107 (P) (T2 Digital Image processing) (IT2 block)","","",""],
  ["CE (17)","","","","","Lunch","","","","",""],
  ["ME (13)","","","","","Lunch","","","","",""],
  ["MT (20)","","","","","Lunch","","","","",""],
  ["NT (6)","","","","","Lunch","","","","",""]
];

mess = [
  ["WADA", "FREE", "FREE", "MIRCHI BHAJJI"],
  ["WHEAT UPMA", "CHAPATHI", "FREE", "UGGANI"],
  ["FRUIT CAKE", "JEERA RICE", "STEAMED RICE", "TEA"],
  ["TEA", "EGG MASALA CURRY", "ALOO PALAK", "COFFEE"],
  ["COFFEE", "KADAI VEG", "PEAS RICE", "BOOST"],
  ["BOOST", "STEEMED RICE", "RASAM", "MILK"],
  ["MILK", "DONDAKAI CHUTNEY", "DAL MAKHANI", "FREE"],
  ["CORN FLAKES/CHOCOS(ALTERNATE DAYS)", "RASAM, SAMBAR", "CURD, PICKLE", "FREE"],
  ["COCONUT CHUTNEY SAMBAR", "CURD", "CUT FRUITS", "FREE"],
  ["GINGER CHUTNEY", "MADATHA KHAJA", "FREE", "FREE"],
  ["FREE", "FREE", "FREE", "FREE"],
  ["SET DOSA", "FREE", "CHICKEN CORN SOUP", "MINI SAMOSA (Onion & corn stuffing)"],
  ["PEAS UPMA", "POORI", "SWEET CORN SOUP", "BLACK CHANNA"],
  ["CHOCOLATE COOKIES", "CORN PULAO", "SCHEZEWAN EGG FRIED RICE", "TANG"],
  ["TEA", "PUNJABI CHOLE MASALA", "SCHEZEWAN VEG FRIED RICE", "FREE"],
  ["COFFEE", "CABBAGE CARROT PORIYAL", "VEG NOODLES", "FREE"],
  ["BOOST", "STEEMED RICE", "EGG NOODLES", "FREE"],
  ["MILK", "DOSAKAI MUKKALA  CHUTNEY", "FRUIT CUSTARD", "FREE"],
  ["CORN FLAKES/CHOCOS(ALTERNATE DAYS)", "PALAKURA PAPPU", "DAL ,RASAM", "FREE"],
  ["BOLIED  EGG", "RASAM", "CURD RICE", "FREE"],
  ["COCONUT CHUTNEY SAMBAR", "CURD", "RASAM", "FREE"],
  ["GINGER CHUTNEY", "KALA JAMUN", "HOT GARLIC SAUSE", "FREE"],
  ["FREE", "FREE", "FREE", "FREE"],
  ["MYSORE BONDA", "FREE", "PULKA", "PAV BHAJI"],
  [
    "HOT PONGAL",
    "PULKA RUMALI ROTI",
    "SAMBAR RICE WITH BOONDHI",
    "BOILED PEANUTS",
  ],
  ["BREAD BUTTER JAM", "ANDHRA CHICKEN", "RAJMA MASALA", "BUTTER MILK"],
  ["TEA", "STEAMED RICE", "STEAMED RICE", "FREE"],
  ["COFFEE", "BAGARA RICE", "DAL TADKA", "FREE"],
  ["BOOST", "PANEER BUTTER MASALA", "FREE", "FREE"],
  ["MILK", "SAMBAR", "FREE", "FREE"],
  [
    "CORN FLAKES/CHOCOS(ALTERNATE DAYS)",
    "TOMATO RASAM",
    "CURD RICE WITH PROMAGRANATE",
    "FREE",
  ],
  ["COCONUT CHUTNEY SAMBAR", "CURD,  PICKLE.", "CUT FRUITS", "FREE"],
  ["GINGER CHUTNEY", "SAGGU BIYAM PAYASAM", "FREE", "FREE"],
  ["FREE", "FREE", "FREE", "FREE"],
  ["ONION UTHAPPAM", "FREE", "KULCHA/BUTTERNAAN", "RAGADA PAPIDI"],
  ["VEG UPMA", "CHAPATHI", "MUTTER PANNER", "BHEL POORI"],
  ["STRAWBERRY MUFFINS", "CHINTHAPANDU PULIHORA", "FREE", "TEA"],
  ["TEA", "ALOO METHI CURRY", "STEAMED RICE", "COFFEE"],
  ["COFFEE", "BRINJAL GREEN PEAS DRY CURRY", "DAL MAKANI", "BOOST"],
  ["BOOST", "STEEMED RICE", "RASAM/SAMBAR", "MILK"],
  ["MILK", "TOMATO KOTHIMERA CHUTNEY", "CURD/PICKLE", "FREE"],
  ["CORN FLAKES/CHOCOS(ALTERNATE DAYS)", "MUDHAPAPPU", "CUT FRUITS", "FREE"],
  ["BOLIED  EGG", "MAJJIGACHARU", "FREE", "FREE"],
  ["COCONUT CHUTNEY SAMBAR", "CURD", "FREE", "FREE"],
  ["FREE", "MAL POORI", "FREE", "FREE"],
  ["FREE", "TANDOORI SALAD", "FREE", "FREE"],
  ["POORI", "FREE", "PULKA\nVEG PULAO", "PIZZA"],
  ["TOMATO BATH", "PULKA", "FREE", "PALLI PAKODI"],
  ["BROWNIE", "EGG BURJI", "FREE", "TEA"],
  ["TEA", "FREE", "3 IN 1 SALAN", "LEMONADE"],
  ["COFFEE", "MUTTER TOMATO KOTHIMEER", "VEG DALCHA", "FREE"],
  ["BOOST", "STEEMED RICE", "STEAMED RICE", "FREE"],
  ["MILK", "FREE", "RAITA", "FREE"],
  [
    "CORN FLAKES/CHOCOS(ALTERNATE DAYS)",
    "SAMBAR",
    "CURD RICE WITH PROMAGRANATE",
    "FREE",
  ],
  ["COCONUT CHUTNEY SAMBAR", "CURD", "CUT FRUITS", "FREE"],
  ["BESAN CURRY", "MOTHICHOOR LADDO", "FREE", "FREE"],
  ["FREE", "FREE", "FREE", "FREE"],
  ["ALOO PAROTA", "FREE", "CHAPATHI", "MAGGIE"],
  ["VEG UPMA", "CHAPATHI", "BEERYAKAYA CHENNA CURRY", "SPROUTS"],
  ["BREAD ,BUTTER, JAM", "GREEN PEAS PULAO", "DAL FRY", "TEA"],
  ["TEA", "DUM ALOO BANARAS", "TOMATO PULAO", "COFFEE"],
  ["COFFEE", "BENDI DO PYASSA, THOTAKOORA DAL", "STEAMED RICE", "BOOST"],
  ["BOOST", "STEEMED RICE", "CURD", "MILK"],
  ["MILK", "GONGURA CHUTNEY", "FREE", "FREE"],
  ["CORN FLAKES/CHOCOS(ALTERNATE DAYS)", "MAJJIGA CHARU", "FREE", "FREE"],
  ["COCONUT CHUTNEY SAMBAR", "CURD", "CUT FRUITS", "FREE"],
  ["GINGER CHUTNEY", "ANNAMAYYA LADOO", "FREE", "FREE"],
  ["FREE", "FREE", "FREE", "FREE"],
  ["DOSA(KARAM,MASALA,PLAIN)", "KEERA,ONION AND LEMON", "WADA", "PANIPOORI"],
  ["VEG UPMA", "PULKA", "VEG UPMA", "DAHI POORI"],
  ["FREE", "CHICKEN BIRYANI", "STEAMED RICE", "TANG"],
  ["TEA", "MUTTER PANEER", "BREAKFAST SAMBAR", "FREE"],
  ["COFFEE", "VEG DUM BIRYANI", "COCONUT CHUTNEY/ KARAM", "FREE"],
  ["BOOST", "STEEMED RICE", "DAL", "FREE"],
  ["MILK", "MIRCHI KA SALAN", "CURD RICE", "FREE"],
  ["CORN FLAKES/CHOCOS(ALTERNATE DAYS)", "RASAM,SAMBAR", "CUT FRUITS", "FREE"],
  ["COCONUT CHUTNEY SAMBAR", "CURD", "FREE", "FREE"],
  ["GINGER CHUTNEY", "COOL DRINKS", "FREE", "FREE"],
];
